### ISSUE TITLE
AWS Elastic Kubernetes: redirect_uri

### ISSUE THREAD

**Issue by schwichti** [simpleidserver/SimpleIdServer#810]
Hi. 
I have adopted [sid-kubernetes.yaml](https://github.com/simpleidserver/SimpleIdServer/blob/master/sid-kubernetes.yaml) to deploy to an EKS cluster:

```yaml
---
# Source: simpleidserver/templates/deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: scim
  namespace: sid
spec:
  type: ClusterIP
  selector:
    app: scim-deploy
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
---
# Source: simpleidserver/templates/deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: idserver
  namespace: sid
spec:
  type: ClusterIP
  selector:
    app: idserver-deploy
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
---
# Source: simpleidserver/templates/deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: sid
spec:
  type: ClusterIP
  selector:
    app: website-deploy
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
---
# Source: simpleidserver/templates/deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: credentialissuer
  namespace: sid
spec:
  type: ClusterIP
  selector:
    app: credentialissuer-deploy
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
---
# Source: simpleidserver/templates/deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: credentialissuerwebsite
  namespace: sid
spec:
  type: ClusterIP
  selector:
    app: credentialissuerwebsite-deploy
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
---
# Source: simpleidserver/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scim-deployment
  namespace: sid
  labels:
    app: scim-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scim-deploy
  template:
    metadata:
      labels:
        app: scim-deploy
    spec:  
      containers:
        - name: scim-deploy
          image: simpleidserver/scim:5.0.2
          ports:
            - containerPort: 80
          env:
            - name: "ASPNETCORE_URLS"
              value: "http://*:80;https://*:443"
            - name: "ASPNETCORE_Kestrel__Certificates__Default__Password"
              value: "password"
            - name: "ASPNETCORE_Kestrel__Certificates__Default__Path"
              value: "/certificates/sid.pfx"
            - name: "ASPNETCORE_FORWARDEDHEADERS_ENABLED"
              value: "true"
            - name: "StorageConfiguration__Type"
              value: POSTGRE
            - name: "StorageConfiguration__ConnectionString"
              valueFrom:
                secretKeyRef:
                  name: scim-config
                  key: StorageConfiguration__ConnectionString
---
# Source: simpleidserver/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idserver-deploy
  namespace: sid
  labels:
    app: idserver-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idserver-deploy
  template:
    metadata:
      labels:
        app: idserver-deploy
    spec:
      containers:
      - name: idserver-deploy
        image: simpleidserver/idserver:5.0.2
        ports:
          - containerPort: 80
        env:
            - name: "ASPNETCORE_URLS"
              value: "http://*:80;https://*:443"    
            - name: "ASPNETCORE_Kestrel__Certificates__Default__Password"
              value: "password"
            - name: "ASPNETCORE_Kestrel__Certificates__Default__Path"
              value: "/certificates/sid.pfx"
            - name: "ASPNETCORE_FORWARDEDHEADERS_ENABLED"
              value: "true"
            - name: "StorageConfiguration__Type"
              value: POSTGRE              
            - name: "SCIMBaseUrl"
              value: "https://scim.mydomain.com"
            - name: "Authority"
              value: "https://idserver.mydomain.com"              
            - name: "SCIM__SCIMRepresentationsExtractionJobOptions__SCIMEdp"
              valueFrom:
                secretKeyRef:
                  name: idserver-config
                  key: StorageConfiguration__ConnectionString
            - name: "StorageConfiguration__ConnectionString"
              valueFrom:
                secretKeyRef:
                  name: idserver-config
                  key: StorageConfiguration__ConnectionString
            - name: "DistributedCacheConfiguration__ConnectionString"
              valueFrom:
                secretKeyRef:
                  name: idserver-config
                  key: StorageConfiguration__ConnectionString
---
# Source: simpleidserver/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
  namespace: sid
  labels:
    app: website-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-deploy
  template:
    metadata:
      labels:
        app: website-deploy
    spec:  
      containers:
      - name: website-deploy
        image: simpleidserver/website:5.0.2
        ports:
        - containerPort: 80
        env:
        - name: "ASPNETCORE_URLS"
          value: "http://*:80;https://*:443"    
        - name: "ASPNETCORE_Kestrel__Certificates__Default__Password"
          value: "password"
        - name: "ASPNETCORE_Kestrel__Certificates__Default__Path"
          value: "/certificates/sid.pfx"
        - name: "ASPNETCORE_FORWARDEDHEADERS_ENABLED"
          value: "true"
        - name: "DefaultSecurityOptions__Issuer"
          value: "https://idserver.mydomain.com"
        - name: "DefaultSecurityOptions__IgnoreCertificateError"
          value: "true"
        - name: "IdServerBaseUrl"
          value: "https://idserver.mydomain.com"
        - name: "ScimBaseUrl"
          value: "https://scim.mydomain.com"
---
# Source: simpleidserver/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credentialissuer-deployment
  namespace: sid
  labels:
    app: credentialissuer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credentialissuer-deploy
  template:
    metadata:
      labels:
        app: credentialissuer-deploy
    spec:
      containers:
        - name: credentialissuer-deploy
          image: simpleidserver/credentialissuer:5.0.2
          ports:
            - containerPort: 80
          env:
            - name: "ASPNETCORE_URLS"
              value: "http://*:80;https://*:443"
            - name: "ASPNETCORE_Kestrel__Certificates__Default__Password"
              value: "password"
            - name: "ASPNETCORE_Kestrel__Certificates__Default__Path"
              value: "/certificates/sid.pfx"
            - name: "ASPNETCORE_FORWARDEDHEADERS_ENABLED"
              value: "true"
            - name: "Authorization__Issuer"
              value: "https://idserver.mydomain.com/master"
---
# Source: simpleidserver/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: credentialissuerwebsite-deploy
  namespace: sid
  labels:
    app: credentialissuerwebsite-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credentialissuerwebsite-deploy
  template:
    metadata:
      labels:
        app: credentialissuerwebsite-deploy
    spec:
      containers:
      - name: credentialissuerwebsite-deploy
        image: simpleidserver/credentialissuerwebsite:5.0.2
        ports:
          - containerPort: 80
        env:
            - name: "ASPNETCORE_URLS"
              value: "http://*:80;https://*:443"    
            - name: "ASPNETCORE_Kestrel__Certificates__Default__Password"
              value: "password"
            - name: "ASPNETCORE_Kestrel__Certificates__Default__Path"
              value: "/certificates/sid.pfx"
            - name: "ASPNETCORE_FORWARDEDHEADERS_ENABLED"
              value: "true"
            - name: "DefaultSecurityOptions__Issuer"
              value: "https://idserver.mydomain.com"
            - name: "DefaultSecurityOptions__IgnoreCertificateError"
              value: "true"
            - name: "CredentialIssuerUrl"
              value: "https://credentialissuer.mydomain.com"
---
# Source: simpleidserver/templates/deployment.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simpleidserver
  namespace: sid
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx  
  tls:
  - hosts:
    - "scim.mydomain.com"
    - "idserver.mydomain.com"
    - "website.mydomain.com"
    - "credentialissuer.mydomain.com"
    - "credentialissuerwebsite.mydomain.com"
    secretName: "certificate" 
  rules:
  - host: "scim.mydomain.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: scim
            port:
              number: 80
  - host: "idserver.mydomain.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: idserver
            port:
              number: 80
  - host: "website.mydomain.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: website
            port:
              number: 80
  - host: "credentialissuer.mydomain.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: credentialissuer
            port:
              number: 80
  - host: "credentialissuerwebsite.mydomain.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: credentialissuerwebsite
            port:
              number: 80
```

When I open https://website.mydomain.com/master/clients in a web browser I am redirected to https://idserver.mydomain.com/master/authorization?client_id=SIDS-manager&redirect_uri=https%3A%2F%2Fwebsite.mydomain.com%2Fmaster%2Fsignin-oidc&response_type=code&scope=openid%20profile%20role&code_challenge=gfPa...&state=CfDJ...&x-client-SKU=ID_NET8_0&x-client-ver=8.0.0.0

which shows the following message:
```json
{
  "error": "invalid_request",
  "error_description": "redirect_uri https://website.mydomain.com/master/signin-oidc is not correct",
  "state": "CfDJ8M...."
}
```

Am I suppose to set the redirect_uri? How can I set it?
